name: Go

on: [ push, pull_request ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@main
      with:
        go-version: '1.22'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6.0.1

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@main
      with:
        go-version: '1.22'

    - name: go test
      run: go test -v ./...